#!/usr/bin/env bash

set -x

# ====== Variables =============================

declare -A gaps
declare -A color

gaps["top"]="4"
gaps["bottom"]="24"
gaps["left"]="4"
gaps["right"]="4"
gaps["inner"]="4"

color["focused"]="0xff775759"
color["normal"]="0x00010101"
color["preselect"]="0xE02d74da"

# Uncomment to refresh ubersicht widget on workspace change
# Make sure to replace WIDGET NAME for the name of the ubersicht widget
#ubersicht_spaces_refresh_command="osascript -e 'tell application id \"tracesOf.Uebersicht\" to refresh widget id \"WIDGET NAME\"'"

# ===== Loading Scripting Additions ============

# See: https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)#macos-big-sur---automatically-load-scripting-addition-on-startup
sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

# ===== Tiling setting =========================

yabai -m config layout                      bsp

yabai -m config top_padding                 "${gaps["top"]}"
yabai -m config bottom_padding              "${gaps["bottom"]}"
yabai -m config left_padding                "${gaps["left"]}"
yabai -m config right_padding               "${gaps["right"]}"
yabai -m config window_gap                  "${gaps["inner"]}"

yabai -m config mouse_follows_focus         off
yabai -m config focus_follows_mouse         off

yabai -m config window_topmost              off
yabai -m config window_opacity              off
yabai -m config window_shadow               float

yabai -m config window_border               on
yabai -m config window_border_width         4
yabai -m config active_window_border_color  "${color["focused"]}"
yabai -m config normal_window_border_color  "${color["normal"]}"
yabai -m config insert_feedback_color       "${color["preselect"]}"

yabai -m config active_window_opacity       1.0
yabai -m config normal_window_opacity       0.90
yabai -m config split_ratio                 0.50

yabai -m config auto_balance                off

yabai -m config mouse_modifier              fn
yabai -m config mouse_action1               move
yabai -m config mouse_action2               resize

# mission-control desktop labels
yabai -m space 1 --label code
yabai -m space 2 --label notes
yabai -m space 3 --label media
yabai -m space 4 --label mob
yabai -m space 5 --label web
yabai -m space 6 --label comms
yabai -m space 7 --label ide

# ===== Rules ==================================

yabai -m rule --add app="^Alacritty$" space=code
yabai -m rule --add app="^Slack$" space=comms
yabai -m rule --add app="^Firefox\ Developer\ Edition$" space=web
yabai -m rule --add app="^Code$" space=notes
yabai -m rule --add app="^Simulator$" space=mob
yabai -m rule --add app="^Xcode$" space=ide
yabai -m rule --add app="^Android\ Studio$" space=ide
yabai -m rule --add app="^qemu_system-x86_64$" space=mob manage=off
yabai -m rule --add app="^React\ Native\ Debugger$" space=mob manage=off
yabai -m rule --add app="^Flipper$" space=mob manage=off
yabai -m rule --add app="^Spotify$" space=media
yabai -m rule --add app="^System Preferences$" manage=off
yabai -m rule --add label="App Store" app="^App Store$" manage=off
yabai -m rule --add label="1Password" app="^1Password 7$" sticky=on layer=above manage=off
yabai -m rule --add app="^Finder$" sticky=on layer=above manage=off
yabai -m rule --add app="^Alfred Preferences$" sticky=on layer=above manage=off
yabai -m rule --add app="^Karabiner-Elements$" sticky=on layer=above manage=off
yabai -m rule --add app="^Karabiner-EventViewer$" sticky=on layer=above manage=off

# ===== Signals ================================


set +x
printf "yabai: configuration loaded...\\n"
