#!/usr/bin/env sh

spacebar -m config position top
spacebar -m config display all
spacebar -m config height 33
spacebar -m config title off
spacebar -m config spaces on
spacebar -m config clock on
spacebar -m config power on
spacebar -m config padding_left 20
spacebar -m config padding_right 20
spacebar -m config spacing_left 25
spacebar -m config spacing_right 15
spacebar -m config text_font "MonoLisa:Regular:14.0"
spacebar -m config icon_font "Font Awesome 5 Free:Solid:14.0"

spacebar -m config power_icon_strip  
spacebar -m config space_icon •
spacebar -m config space_icon_strip 1 2 3 4 5 6 7 8 9 10
spacebar -m config spaces_for_all_displays on
spacebar -m config clock_icon 
spacebar -m config dnd_icon 
spacebar -m config clock_format "%d/%m/%y %R"
spacebar -m config right_shell off
spacebar -m config right_shell_icon 
spacebar -m config right_shell_command "whoami"

# spacebar -m config background_color            0xff1E1C31
# spacebar -m config foreground_color            0xffa8a8a8
# spacebar -m config power_icon_color            0xffF02E6E
# spacebar -m config battery_icon_color          0xffF02E6E
# spacebar -m config dnd_icon_color              0xffa8a8a8
# spacebar -m config cloc_icon_color             0xff62D196

echo "spacebar configuration loaded.."
