wtf:
  colors:
    background: black
    border:
      focusable: darkslateblue
      focused: orange
      normal: gray
    checked: bluesteel
    highlight: 
      fore: black
      back: gray
    rows:
      even: bluestell
      odd: white  
  refreshInterval: 1
  mods:
    gcal:
      colors:
        title: "lightseagreen"
        eventTime: "lightblue"
        description: "aquamarine"
        highlights:
        - ['1on1|1\/11', 'green']
        - ['apple|google|aws', 'blue']
        - ['interview|meet', 'magenta']
        - ['lunch', 'yellow']
        past: "gray"
      calendarReadLevel: "reader"
      conflictIcon: "🚨"
      currentIcon: "💥"
      displayResponseStatus: true
      email: "jamesg2.best@gmail.com"
      enabled: true
      eventCount: 15
      hourFormat: "12"
      multiCalendar: true
      position:
        top: 0
        left: 0
        height: 3
        width: 1
      refreshInterval: 300
      secretFile: "~/.config/wtf/gcal/client_secret.json"
      showDeclined: true
      showEndTime: true
      timezone: "Europe/London"
      withLocation: true
    jira:
      apiKey: "Eq0tXkSBSBB6Vo4UeEFs6686"
      colors:
        rows:
          even: "lightblue"
          odd: "white"
      domain: "https://breedr.atlassian.net"
      email: "james.best@breedr.co"
      enabled: true
      position:
        top: 0
        left: 1
        height: 1
        width: 2
      project: "BRDRCL"
      refreshInterval: 900
      username: "60a679c3c8c05a00694fa71f"
      verifyServerCertificate: false
    gitlab:
      apiKey: "zZETNfxPDkpCTzm4h4x4"
      enabled: true
      position:
        top: 0
        left: 3
        height: 1
        width: 2
      projects:
        - "breedr-trading/breedr-mobile"
      refreshInterval: 300
      username: "wtfutil"
    git:
      commitCount: 5
      commitFormat: "[forestgreen]%h [grey]%cd [white]%s [grey]%an[white]"
      dateFormat: "%H:%M %d %b %y"
      enabled: true
      position:
        top: 1
        left: 3
        height: 1
        width: 2
      refreshInterval: 8
      repositories:
        - "/Users/jamesbest/code/work/breedr-mobile"
        - "/Users/jamesbest/dotfiles"
    feedreader:
      border: true
      enabled: true
      feeds:
      - https://news.ycombinator.com/rss
      feedLimit: 10
      focusable: true
      position:
        top: 1
        left: 1
        width: 1
        height: 1
      title: "Hacker News"
      refreshInterval: 14400
    todoist:
      apiKey: "1c2733b28d98aca6470d4aeff7681ee18b8c2802"
      enabled: true
      title: "Todo"
      position:
        top: 1
        left: 2
        height: 1
        width: 1
      projects:
        - 2267902667
      refreshInterval: 3600
    ipinfo:
      colors:
        name: "lightblue"
        value: "white"
      enabled: true
      position:
        top: 2
        left: 1
        height: 1
        width: 1
      refreshInterval: 150
    power:
      enabled: true
      position:
        top: 2
        left: 2
        height: 1
        width: 1
      refreshInterval: 15
      title: "⚡️"
    docker:
      type: docker
      enabled: true
      labelColor: lightblue
      position:
        top: 2
        left: 3
        height: 1
        width: 1
      refreshInterval: 1
    prettyweather:
      enabled: true
      city: "bristol"
      position:
          top: 2
          left: 4
          height: 1
          width: 1
      refreshInterval: 300
      unit: "m"
      view: 0
      language: "en"
