active_provider: openai # default if a GitHub token is found
language: en # commit message language: "en" (English) or "es" (Spanish)
providers:
  openai:
    api_key: "$OPENAI_API_KEY"
    model: "gpt-4o"
